<div style="background:linear-gradient(to right,#4A148C,#7B2CBF,#C77DFF);
padding:20px;
border-radius:18px;
text-align:center;">

<h1 style="color:white;
font-size:40px;
font-family:Georgia;
margin:0;">
 SALES PREDICTION SYSTEM 📈
</h1>
</div>

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Generating the Synthetic data
</h2>

In [1]:
import numpy as np
import pandas as pd

np.random.seed(15)
n_records = 1000

data = {
    # Basic sales/store info
    "Store_ID": [f"Store{i:03d}" for i in range(1, n_records + 1)],
    "Product_Category": np.random.choice(["Electronics", "Clothing", "Grocery", "Furniture"], n_records),
    "Region": np.random.choice(["North", "South", "East", "West"], n_records),
    "Sales_Channel": np.random.choice(["Online", "Offline"], n_records),

    # Product / pricing features
    "Product_Price": np.random.randint(200, 5000, n_records),
    "Discount_Percentage": np.random.randint(0, 51, n_records),
    "Competitor_Price": np.random.randint(150, 4800, n_records),

    # Marketing / promotion features
    "Marketing_Spend": np.random.randint(1000, 50000, n_records),
    "Ad_Clicks": np.random.randint(50, 5000, n_records),
    "Promotional_Offer": np.random.choice([0, 1], n_records, p=[0.6, 0.4]),

    # Time / seasonal features
    "Month": np.random.randint(1, 13, n_records),
    "Weekend_Sales": np.random.choice([0, 1], n_records, p=[0.4, 0.6]),
    "Holiday_Season": np.random.choice([0, 1], n_records, p=[0.7, 0.3]),

    # Inventory / customer behaviour
    "Stock_Available": np.random.randint(10, 500, n_records),
    "Customer_Rating": np.clip(np.random.normal(4.0, 0.7, n_records), 1, 5).round(1),
    "Return_Rate": np.clip(np.random.normal(8, 4, n_records), 0, 30).round(1),

    # Target variable
    "Units_Sold": np.random.randint(20, 500, n_records)
}

df_sales = pd.DataFrame(data)

df_sales

,Store_ID,Product_Category,Region,Sales_Channel,Product_Price,Discount_Percentage,Competitor_Price,Marketing_Spend,Ad_Clicks,Promotional_Offer,Month,Weekend_Sales,Holiday_Season,Stock_Available,Customer_Rating,Return_Rate,Units_Sold
0,Store001,Electronics,East,Offline,2172,18,4448,3901,2845,0,6,1,0,49,4.1,6.1,314
1,Store002,Clothing,South,Offline,3337,37,1298,1791,248,0,1,1,0,421,4.7,11.5,325
2,Store003,Electronics,East,Offline,4983,34,4700,11879,1267,0,1,1,0,396,3.9,7.5,465
3,Store004,Clothing,East,Offline,2873,35,4440,39700,326,0,8,0,0,20,5.0,8.9,369
4,Store005,Furniture,West,Offline,580,34,1186,8496,194,1,1,0,0,488,2.8,8.0,439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Store996,Clothing,East,Online,1689,38,2169,31622,3853,1,1,1,1,80,5.0,12.8,306
996,Store997,Furniture,South,Online,4549,35,3906,19428,3332,0,9,1,1,351,4.2,8.1,89
997,Store998,Electronics,North,Online,4392,27,3404,24654,1619,0,2,1,0,281,4.4,2.2,436
998,Store999,Furniture,South,Offline,2358,28,2236,13179,4447,0,7,1,0,50,3.7,0.5,139
999,Store1000,Grocery,East,Offline,3018,17,950,48559,2879,0,9,0,0,56,5.0,17.4,126

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊  Calculating the Risk Score
</h2>

In [8]:
risk_score = (
    0.20 * (df_sales["Discount_Percentage"] < 10).astype(int) +
    0.15 * (df_sales["Marketing_Spend"] < 10000).astype(int) +
    0.15 * (df_sales["Customer_Rating"] < 3.5).astype(int) +
    0.10 * (df_sales["Return_Rate"] > 15).astype(int) +
    0.10 * (df_sales["Stock_Available"] > 300).astype(int) +
    0.10 * (df_sales["Product_Price"] > 3000).astype(int) +
    0.05 * (df_sales["Promotional_Offer"] == 0).astype(int) +
    0.05 * (df_sales["Holiday_Season"] == 0).astype(int) +
    0.05 * (df_sales["Weekend_Sales"] == 0).astype(int) +
    0.05 * (df_sales["Units_Sold"] < 80).astype(int)
)

df_sales["Risk_Score"] = risk_score.round(2)

df_sales

,Store_ID,Product_Category,Region,Sales_Channel,Product_Price,Discount_Percentage,Competitor_Price,Marketing_Spend,Ad_Clicks,Promotional_Offer,Month,Weekend_Sales,Holiday_Season,Stock_Available,Customer_Rating,Return_Rate,Units_Sold,Risk_Score
0,Store001,Electronics,East,Offline,2172,18,4448,3901,2845,0,6,1,0,49,4.1,6.1,314,0.25
1,Store002,Clothing,South,Offline,3337,37,1298,1791,248,0,1,1,0,421,4.7,11.5,325,0.45
2,Store003,Electronics,East,Offline,4983,34,4700,11879,1267,0,1,1,0,396,3.9,7.5,465,0.30
3,Store004,Clothing,East,Offline,2873,35,4440,39700,326,0,8,0,0,20,5.0,8.9,369,0.15
4,Store005,Furniture,West,Offline,580,34,1186,8496,194,1,1,0,0,488,2.8,8.0,439,0.50
5,Store006,Electronics,East,Offline,4485,17,2238,42852,2205,0,4,1,0,94,2.7,4.9,474,0.35
6,Store007,Electronics,West,Online,3550,45,3299,43321,4701,0,10,1,1,446,4.3,4.3,461,0.25
7,Store008,Furniture,South,Online,3944,15,987,41658,1841,0,10,1,1,237,3.6,2.5,459,0.15
8,Store009,Furniture,East,Offline,1032,33,725,21305,1185,1,7,0,1,74,3.2,1.7,70,0.25
9,Store010,Furniture,South,Online,4269,50,1718,17201,4330,0,9,1,1,443,4.6,1.0,465,0.25
10,Store011,Clothing,West,Online,3698,1,3415,37721,1646,0,5,1,0,428,3.6,8.3,446,0.50
11,Store012,Grocery,West,Offline,622,49,3879,19198,3863,1,11,0,1,181,3.8,6.2,356,0.05
12,Store013,Furniture,South,Offline,1991,19,4652,27423,4452,0,11,1,0,34,5.0,6.6,311,0.10
13,Store014,Clothing,West,Offline,2771,49,2890,40541,564,0,1,0,1,248,3.9,5.3,204,0.10
14,Store015,Clothing,North,Offline,909,42,201,9647,555,1,9,0,0,184,4.5,8.4,402,0.25
15,Store016,Clothing,North,Online,2344,43,4216,38945,4287,0,5,1,0,463,5.0,5.2,220,0.20
16,Store017,Furniture,North,Online,2710,43,1325,22111,72,1,11,1,1,476,2.5,8.0,401,0.25
17,Store018,Furniture,East,Offline,1592,3,4205,40141,4635,0,1,1,0,175,4.4,8.4,72,0.35
18,Store019,Electronics,East,Online,3333,12,2561,9540,3536,0,12,1,0,277,3.9,11.6,308,0.35
19,Store020,Grocery,West,Online,1898,47,1003,11136,4470,1,12,0,1,354,4.1,9.6,439,0.15
20,Store021,Grocery,West,Online,457,50,1250,17309,1853,1,6,0,1,382,2.8,11.6,238,0.30
21,Store022,Furniture,North,Offline,3092,38,158,10751,1091,0,10,1,0,26,2.7,12.1,359,0.35
22,Store023,Electronics,West,Online,3654,16,1357,5398,4937,1,5,0,1,262,2.6,6.3,293,0.45
23,Store024,Clothing,South,Online,3711,42,2087,8717,2684,0,8,1,1,295,4.1,9.5,462,0.30
24,Store025,Furniture,East,Offline,4447,46,2721,21617,2754,0,9,1,1,165,4.1,0.6,133,0.15
25,Store026,Clothing,West,Online,1445,29,3713,23149,4642,0,3,0,0,399,4.0,1.7,456,0.25
26,Store027,Furniture,West,Online,764,3,4165,7731,2240,1,7,1,0,441,2.8,17.0,120,0.75
27,Store028,Electronics,East,Offline,3549,44,2574,24845,1251,1,2,1,1,341,4.6,2.1,153,0.20
28,Store029,Clothing,North,Online,2898,37,2088,4886,2679,0,9,1,0,461,3.6,12.0,409,0.35
29,Store030,Electronics,East,Offline,4927,6,4441,29318,2359,0,8,1,1,285,2.5,12.3,128,0.50
30,Store031,Clothing,North,Online,4147,8,2576,2851,4136,0,10,0,0,72,4.3,1.3,320,0.60
31,Store032,Furniture,North,Offline,4367,29,3605,13462,448,0,3,0,0,123,3.2,8.3,367,0.40
32,Store033,Grocery,East,Offline,3520,9,3062,37339,4726,0,10,1,0,373,4.1,4.2,252,0.50
33,Store034,Furniture,West,Offline,4998,23,1803,5451,788,0,3,1,1,326,4.7,8.6,215,0.40
34,Store035,Electronics,West,Online,2186,44,2642,37947,3336,0,12,1,0,144,3.5,9.9,439,0.10
35,Store036,Grocery,West,Offline,4182,23,2071,23991,2651,1,4,0,0,14,4.8,7.6,30,0.25
36,Store037,Clothing,North,Offline,4843,20,3164,5397,4083,1,11,0,0,343,3.2,14.0,119,0.60
37,Store038,Clothing,South,Online,2948,46,3750,4042,1399,0,12,0,0,427,4.0,8.0,309,0.40
38,Store039,Furniture,West,Online,278,20,3950,26547,1852,1,4,1,1,462,4.8,11.5,233,0.10
39,Store040,Electronics,South,Online,1003,33,4607,29996,1965,0,10,1,0,348,4.9,9.8,284,0.20
40,Store041,Clothing,North,Online,900,1,3007,12800,731,1,1,0,0,477,3.8,7.6,308,0.40
41,Store042,Grocery,West,Online,1977,34,2642,12692,226,0,1,0,0,121,4.2,8.9,282,0.15
42,Store043,Grocery,West,Online,2858,26,236,15123,2832,1,10,0,0,139,3.9,10.0,351,0.10
43,Store044,Furniture,West,Offline,2777,3,4466,28599,4230,1,5,0,0,157,4.0,18.2,176,0.40
44,Store045,Grocery,South,Offline,4887,16,1201,15377,2830,0,3,1,0,79,5.0,8.9,31,0.25
45,Store046,Clothing,North,Offline,1569,23,1163,35590,1246,1,11,0,0,125,3.7,0.8,467,0.10
46,Store047,Electronics,East,Online,934,13,1826,16403,4023,1,11,0,0,180,2.6,8.1,393,0.25
47,Store048,Clothing,East,Offline,233,15,2443,19457,1679,1,2,0,0,312,4.2,5.7,459,0.20
48,Store049,Grocery,West,Online,2713,17,3273,1534,4654,0,10,1,0,19,5.0,3.3,433,0.25
49,Store050,Clothing,South,Online,2518,34,1776,32982,4905,1,3,1,0,468,3.7,7.8,306,0.15
50,Store051,Grocery,North,Offline,2687,21,3584,2401,1185,0,12,1,0,474,4.7,4.4,196,0.35
51,Store052,Electronics,East,Offline,1814,33,3874,25289,1756,0,9,0,0,145,2.5,8.6,489,0.30
52,Store053,Grocery,North,Online,2659,11,681,27282,3274,0,4,1,0,156,3.3,11.3,311,0.25
53,Store054,Furniture,West,Offline,3590,29,2903,14163,3791,0,12,1,1,492,4.7,5.9,278,0.25
54,Store055,Electronics,West,Online,923,10,1955,1322,963,0,8,1,0,76,3.8,4.0,217,0.25
55,Store056,Furniture,West,Online,4626,32,2538,38783,2375,0,4,1,1,435,3.8,9.6,325,0.25
56,Store057,Electronics,East,Offline,4147,0,4396,46982,3988,0,3,1,1,265,4.1,8.2,481,0.35
57,Store058,Electronics,East,Online,586,24,3728,29737,2490,1,11,1,0,106,4.0,10.4,292,0.05
58,Store059,Furniture,North,Offline,1230,46,3731,2430,2486,0,6,0,0,117,3.8,6.2,177,0.30
59,Store060,Electronics,North,Offline,4912,41,3390,36002,2886,0,5,1,1,330,4.2,0.5,64,0.30
60,Store061,Furniture,West,Offline,3008,32,245,13644,3722,0,12,0,0,412,2.7,8.9,479,0.50
61,Store062,Grocery,West,Online,1088,27,2406,4442,746,0,11,0,0,356,3.9,9.3,123,0.40
62,Store063,Grocery,North,Online,4004,3,3508,12282,297,1,8,1,0,295,4.2,8.3,377,0.35
63,Store064,Electronics,North,Online,854,27,312,2037,4512,0,2,0,0,167,4.0,11.0,45,0.35
64,Store065,Clothing,West,Online,4263,9,3696,36586,4338,0,3,1,0,27,3.6,5.1,353,0.40
65,Store066,Furniture,North,Online,571,15,4488,30721,1677,0,11,1,0,318,3.3,14.0,202,0.35
66,Store067,Furniture,North,Offline,1556,12,3283,36842,1307,1,11,0,0,424,4.0,9.5,169,0.20
67,Store068,Electronics,West,Online,3505,35,289,28666,4223,0,9,1,0,367,3.8,11.4,79,0.35
68,Store069,Clothing,North,Online,1664,34,1950,35401,4220,0,7,1,1,456,4.8,12.3,135,0.15
69,Store070,Electronics,East,Online,293,35,4628,38652,735,1,7,1,0,265,4.5,7.4,356,0.05
70,Store071,Clothing,West,Offline,539,26,1279,13809,3398,0,5,1,0,14,4.5,8.1,208,0.10
71,Store072,Furniture,West,Offline,1887,47,3425,42384,257,0,10,1,1,102,2.8,13.8,58,0.25
72,Store073,Clothing,South,Online,4120,28,2574,17210,2778,1,1,0,0,445,4.1,7.4,163,0.30
73,Store074,Electronics,South,Offline,1537,34,3164,9278,3733,0,8,1,0,375,3.1,10.4,96,0.50
74,Store075,Electronics,South,Offline,4573,39,4480,33806,3890,0,4,0,0,166,3.9,9.2,404,0.25
75,Store076,Furniture,East,Online,266,50,2663,22329,3071,0,7,1,0,249,2.9,10.2,187,0.25
76,Store077,Clothing,North,Online,4761,7,3422,3750,2570,0,5,1,0,156,4.7,4.2,244,0.55
77,Store078,Clothing,South,Online,2968,16,407,40486,3926,0,7,0,0,411,3.6,13.7,63,0.30
78,Store079,Electronics,East,Online,3391,46,4385,48772,3932,1,3,1,0,150,4.8,9.0,342,0.15
79,Store080,Electronics,East,Offline,1464,29,3926,3467,4073,0,2,1,1,223,4.5,12.2,63,0.25
80,Store081,Grocery,North,Offline,4405,17,2423,31938,4493,0,10,1,0,253,2.4,4.4,173,0.35
81,Store082,Grocery,North,Offline,3917,36,884,44005,4740,0,4,1,1,56,4.3,2.7,440,0.15
82,Store083,Electronics,West,Offline,3125,22,3286,46665,811,1,9,1,0,121,4.8,12.1,390,0.15
83,Store084,Clothing,East,Offline,314,6,3391,4269,395,0,11,0,1,194,4.0,3.6,78,0.50
84,Store085,Grocery,West,Offline,1194,5,4641,24317,2001,0,12,1,1,437,4.0,10.9,325,0.35
85,Store086,Electronics,South,Online,2647,20,4374,30635,4689,0,5,1,1,40,3.9,3.3,221,0.05
86,Store087,Electronics,North,Online,3994,6,1197,14881,4360,1,3,1,0,382,4.1,5.6,481,0.45
87,Store088,Furniture,East,Offline,4158,29,1515,39642,344,1,1,1,0,389,5.0,10.0,445,0.25
88,Store089,Grocery,West,Offline,2597,25,750,42284,3884,0,1,0,0,332,4.2,15.7,137,0.35
89,Store090,Clothing,West,Offline,308,37,606,11964,3958,1,4,1,0,231,4.5,6.3,343,0.05
90,Store091,Furniture,West,Online,1467,16,3073,20772,2398,1,4,1,1,22,4.0,4.8,370,0.00
91,Store092,Grocery,West,Online,4152,42,4774,5707,1637,0,6,1,0,437,5.0,15.5,320,0.55
92,Store093,Furniture,North,Online,2128,21,4694,27354,3444,0,11,1,0,285,3.4,5.7,47,0.30
93,Store094,Clothing,South,Online,3028,8,3702,35255,269,1,1,0,0,455,3.5,11.1,414,0.50
94,Store095,Clothing,West,Online,4072,10,3945,23155,1249,0,8,1,0,97,4.6,1.4,112,0.20
95,Store096,Grocery,West,Online,2075,43,517,44331,3417,0,4,1,1,371,4.6,7.3,446,0.15
96,Store097,Furniture,North,Online,414,23,4606,25654,3583,1,4,1,0,145,2.6,15.4,105,0.30
97,Store098,Grocery,North,Online,2602,38,1345,36467,2317,0,8,1,1,153,3.8,8.9,62,0.10
98,Store099,Grocery,East,Online,2233,11,2982,21199,200,0,8,1,0,110,4.0,9.5,278,0.10
99,Store100,Grocery,South,Offline,4367,13,1076,32511,4821,1,12,0,0,238,2.5,4.8,372,0.35
100,Store101,Electronics,West,Online,2792,22,1442,10831,404,0,11,1,0,171,5.0,6.3,21,0.15
101,Store102,Clothing,East,Online,3177,36,1686,26039,227,0,1,0,0,492,3.9,5.2,279,0.35
102,Store103,Grocery,East,Offline,1268,26,648,20521,1975,1,12,1,1,326,5.0,4.7,190,0.10
103,Store104,Electronics,East,Offline,2772,7,4429,18238,1791,1,4,0,0,146,4.5,8.4,78,0.35
104,Store105,Furniture,North,Offline,1720,33,2934,31158,3953,1,1,0,0,335,5.0,9.5,208,0.20
105,Store106,Grocery,North,Online,588,15,378,16731,884,1,10,1,0,292,4.3,5.9,92,0.05
106,Store107,Electronics,East,Offline,3026,29,1712,37156,4223,1,7,1,0,296,3.4,6.1,348,0.30
107,Store108,Electronics,West,Offline,3768,21,2928,48537,4233,1,1,1,0,73,4.9,0.5,233,0.15
108,Store109,Electronics,North,Offline,3729,15,1716,18932,828,0,1,1,0,21,4.6,11.7,495,0.20
109,Store110,Furniture,North,Online,4067,8,3492,14200,3490,0,3,1,0,467,4.5,12.9,83,0.50
110,Store111,Furniture,South,Online,4031,47,2377,18185,3427,0,7,1,0,163,4.5,7.4,372,0.20
111,Store112,Electronics,South,Offline,2279,17,2171,7754,568,1,4,1,1,25,5.0,6.7,201,0.15
112,Store113,Clothing,East,Offline,462,20,4263,14239,1588,1,5,1,1,123,4.1,16.6,476,0.10
113,Store114,Grocery,South,Offline,3562,47,3602,2035,2743,0,2,0,1,271,4.2,1.6,141,0.35
114,Store115,Electronics,West,Online,4876,28,4317,9384,2373,0,7,1,0,326,4.2,11.9,290,0.45
115,Store116,Clothing,North,Offline,2303,35,1103,4544,4648,0,8,1,1,369,3.7,3.3,81,0.30
116,Store117,Electronics,East,Offline,4357,50,1245,30183,4490,0,4,0,0,338,4.5,14.8,142,0.35
117,Store118,Electronics,North,Online,3002,26,2548,12789,4621,0,9,0,0,483,3.1,8.1,341,0.50
118,Store119,Electronics,South,Offline,796,46,3270,18058,2786,0,10,1,0,124,4.5,5.4,35,0.15
119,Store120,Grocery,East,Offline,2572,40,2841,4891,4245,1,2,1,0,349,3.4,1.8,269,0.45
120,Store121,Grocery,North,Offline,3368,49,2853,3282,1453,1,10,0,1,327,3.2,8.3,393,0.55
121,Store122,Furniture,South,Online,1863,16,3554,35855,915,0,4,1,1,460,4.5,5.8,299,0.15
122,Store123,Grocery,North,Offline,1508,13,4113,35435,3521,1,11,1,0,11,4.3,3.1,20,0.10
123,Store124,Grocery,South,Online,2315,14,1609,22291,1060,0,5,1,0,364,3.2,12.0,488,0.35
124,Store125,Furniture,South,Offline,3326,25,2153,47640,3920,1,4,1,1,482,4.4,3.0,263,0.20
125,Store126,Electronics,North,Online,3917,21,3370,49239,4017,1,9,0,1,176,3.1,5.1,119,0.30
126,Store127,Grocery,North,Online,4283,29,1373,17086,1993,0,3,1,0,449,3.7,5.5,281,0.30
127,Store128,Electronics,East,Online,857,50,3089,24055,2983,1,11,1,0,423,3.0,19.7,105,0.40
128,Store129,Grocery,West,Offline,3577,10,1952,34672,4937,1,6,0,0,182,5.0,10.4,146,0.20
129,Store130,Grocery,South,Online,3591,16,465,15578,375,0,12,1,1,333,3.7,9.9,84,0.25
130,Store131,Clothing,East,Offline,571,34,3333,12886,3517,0,2,0,0,453,4.2,6.3,496,0.25
131,Store132,Furniture,North,Online,508,8,4287,27075,3796,1,9,1,0,259,4.8,6.5,113,0.25
132,Store133,Furniture,North,Online,702,38,3307,26142,4308,0,1,0,0,288,4.4,6.9,61,0.20
133,Store134,Electronics,West,Offline,4174,42,1541,27741,3525,1,3,1,0,449,3.8,5.7,381,0.25
134,Store135,Furniture,West,Online,3632,31,4545,31871,4723,0,9,1,0,43,3.8,3.4,192,0.20
135,Store136,Clothing,South,Online,4959,14,3618,4882,2322,0,3,1,0,285,3.9,11.9,300,0.35
136,Store137,Electronics,North,Online,1078,0,3811,23024,245,0,9,1,0,25,4.4,4.2,421,0.30
137,Store138,Furniture,South,Online,1435,36,259,30829,2734,0,1,0,0,499,3.5,8.6,361,0.25
138,Store139,Furniture,West,Online,2308,41,496,44465,2069,0,7,1,0,337,3.5,5.0,75,0.25
139,Store140,Electronics,South,Online,1549,50,4740,25623,1197,1,9,1,0,300,4.4,15.2,275,0.15
140,Store141,Furniture,North,Online,3274,34,648,13486,3117,0,7,1,0,207,5.0,0.0,23,0.25
141,Store142,Furniture,West,Offline,4122,41,2056,47250,3243,1,10,0,0,72,2.9,8.3,357,0.35
142,Store143,Electronics,North,Online,3686,34,2592,13596,2740,0,1,1,0,108,2.8,11.5,393,0.35
143,Store144,Grocery,West,Online,3327,44,3103,28781,3987,0,12,0,0,241,4.1,14.6,398,0.25
144,Store145,Clothing,East,Offline,2782,46,1044,3199,4132,0,7,1,0,218,4.8,5.7,400,0.25
145,Store146,Grocery,East,Online,1826,41,3984,6678,4323,1,6,1,0,386,3.8,10.6,159,0.30
146,Store147,Grocery,South,Online,2358,13,3867,33730,3175,0,5,0,1,366,3.9,8.5,449,0.20
147,Store148,Clothing,South,Online,4811,28,190,17388,483,1,11,0,0,303,3.5,0.3,242,0.30
148,Store149,Electronics,North,Online,4741,33,3398,35178,800,0,2,0,0,181,4.5,11.5,100,0.25
149,Store150,Electronics,West,Online,2264,0,1082,39977,1242,1,3,1,1,136,4.4,14.1,351,0.20
150,Store151,Furniture,West,Offline,4974,48,1090,20464,4193,0,4,1,0,218,3.0,5.3,75,0.40
151,Store152,Grocery,North,Online,508,5,3318,3879,1488,0,12,0,0,286,3.9,8.2,372,0.50
152,Store153,Electronics,North,Online,4637,23,2207,11036,2442,0,11,1,0,270,3.7,6.3,476,0.20
153,Store154,Electronics,South,Online,379,3,1338,9302,677,1,7,1,0,240,3.7,8.6,452,0.40
154,Store155,Furniture,South,Online,3412,26,3423,16979,1619,0,6,1,0,13,3.8,2.8,225,0.20
155,Store156,Grocery,North,Online,1918,17,1924,7055,4562,1,3,1,1,402,4.2,15.3,138,0.35
156,Store157,Grocery,North,Online,904,33,3639,5500,96,1,4,0,1,190,4.6,8.2,255,0.20
157,Store158,Furniture,South,Offline,4208,46,3650,2037,377,0,1,1,0,185,4.5,15.1,415,0.45
158,Store159,Furniture,East,Offline,2375,39,3786,32044,1821,1,1,1,0,404,4.9,11.3,342,0.15
159,Store160,Clothing,North,Offline,1204,41,4402,40115,1728,1,11,0,0,178,3.8,6.0,338,0.10
160,Store161,Clothing,West,Offline,1430,10,3981,21920,3415,0,11,1,0,195,4.1,6.3,405,0.10
161,Store162,Grocery,East,Online,4336,37,1420,42416,794,1,2,1,1,210,4.4,8.9,153,0.10
162,Store163,Electronics,West,Offline,2889,27,3469,43085,2025,0,5,0,1,311,3.5,8.8,144,0.20
163,Store164,Furniture,East,Online,727,38,656,26888,1966,1,10,0,0,119,3.7,10.1,465,0.10
164,Store165,Clothing,North,Offline,1856,41,3969,32036,3438,1,3,0,0,49,4.7,3.9,21,0.15
165,Store166,Electronics,South,Online,4719,13,2887,31749,3300,0,11,1,1,293,3.7,14.5,101,0.15
166,Store167,Furniture,East,Online,1941,5,1409,44625,3246,0,3,1,0,319,3.9,5.0,340,0.40
167,Store168,Furniture,West,Online,972,4,1431,16395,3675,0,10,1,1,365,4.6,0.0,420,0.35
168,Store169,Electronics,North,Offline,1757,18,3671,20528,3323,0,3,0,0,240,4.2,6.1,58,0.20
169,Store170,Electronics,East,Online,2011,21,2175,20550,4136,0,10,1,0,87,4.5,6.1,230,0.10
170,Store171,Furniture,North,Online,1017,29,4528,37536,3654,0,1,1,1,388,4.6,7.3,254,0.15
171,Store172,Clothing,West,Offline,4836,35,1495,35864,2673,0,2,0,0,113,2.8,6.4,202,0.40
172,Store173,Electronics,East,Offline,2528,35,1310,27997,1199,1,10,1,0,103,2.6,6.5,144,0.20
173,Store174,Clothing,South,Offline,2319,25,1938,26171,123,0,8,0,0,191,4.2,5.6,451,0.15
174,Store175,Electronics,West,Offline,4054,24,516,14440,4468,0,2,1,1,129,4.2,5.6,246,0.15
175,Store176,Clothing,West,Online,3332,8,2509,2664,3245,0,6,1,0,138,4.8,8.1,292,0.55
176,Store177,Electronics,West,Online,4583,27,1124,9347,2003,1,2,0,0,294,4.5,14.1,46,0.40
177,Store178,Electronics,North,Online,3214,21,248,2755,3327,1,3,1,0,101,3.0,7.5,382,0.45
178,Store179,Grocery,South,Offline,2984,43,2128,33662,892,0,6,1,0,389,3.9,4.5,68,0.25
179,Store180,Furniture,East,Offline,744,1,3681,7544,2868,1,6,1,0,245,3.6,5.3,289,0.40
180,Store181,Clothing,North,Online,3992,8,1760,13263,1713,1,7,0,1,161,3.5,12.7,366,0.35
181,Store182,Electronics,South,Offline,4698,25,3899,45787,3842,0,11,1,0,224,3.0,10.3,83,0.35
182,Store183,Electronics,North,Online,696,40,4444,48127,2106,0,2,0,1,394,3.5,1.7,117,0.20
183,Store184,Clothing,North,Offline,4948,37,3410,2523,829,1,9,0,0,359,5.0,13.5,237,0.45
184,Store185,Furniture,South,Online,2434,22,1213,16146,4063,0,5,1,0,319,4.4,0.0,394,0.20
185,Store186,Electronics,East,Offline,1353,7,3082,6524,2203,0,9,0,0,429,3.9,6.7,184,0.60
186,Store187,Clothing,West,Offline,909,0,3890,30100,4623,1,8,0,0,491,4.1,14.9,141,0.40
187,Store188,Furniture,East,Offline,2827,7,1550,12159,161,0,10,1,0,415,3.6,4.6,244,0.40
188,Store189,Clothing,North,Offline,4475,50,4155,22454,1356,1,10,1,0,253,4.8,5.6,139,0.15
189,Store190,Furniture,North,Online,299,35,928,43148,2912,0,8,0,0,434,3.7,9.3,109,0.25
190,Store191,Electronics,East,Online,1310,19,694,2418,1329,1,7,0,0,262,4.9,6.5,241,0.25
191,Store192,Electronics,South,Offline,1769,39,3477,26499,1824,0,7,0,0,234,4.3,5.1,132,0.15
192,Store193,Electronics,West,Offline,1842,1,724,18720,2971,1,11,1,1,370,3.3,13.7,303,0.45
193,Store194,Furniture,West,Online,3860,34,4303,14248,2165,1,5,1,1,57,2.9,10.2,120,0.25
194,Store195,Clothing,West,Offline,3254,2,4048,17809,4985,1,3,0,0,386,4.0,3.5,183,0.50
195,Store196,Clothing,South,Offline,4914,23,4246,35126,3079,0,11,1,0,412,3.7,5.4,222,0.30
196,Store197,Grocery,East,Online,3428,3,2636,8421,2531,0,4,0,0,191,2.5,5.8,301,0.75
197,Store198,Electronics,North,Online,1985,33,4294,17262,1393,0,5,1,0,21,5.0,5.1,276,0.10
198,Store199,Clothing,West,Offline,3158,48,3454,47747,807,0,10,0,1,426,4.7,6.7,184,0.30
199,Store200,Furniture,West,Online,3502,17,1525,41330,2891,1,3,0,0,307,4.8,8.1,415,0.30
200,Store201,Furniture,West,Online,2530,28,1721,10766,4490,0,11,1,0,392,4.6,5.5,136,0.20
201,Store202,Electronics,North,Online,1427,28,1888,18428,1767,0,3,1,1,309,2.8,6.1,136,0.30
202,Store203,Furniture,West,Online,4866,5,535,6512,992,1,2,0,0,315,2.4,4.3,121,0.80
203,Store204,Electronics,East,Online,1853,48,2351,36747,2815,0,2,1,0,76,3.9,9.2,110,0.10
204,Store205,Furniture,North,Online,1219,49,2552,33599,2768,0,6,1,0,497,2.6,5.5,419,0.35
205,Store206,Furniture,East,Online,3827,19,1164,30948,1378,0,9,0,1,213,5.0,2.2,354,0.20
206,Store207,Furniture,North,Online,4342,45,3652,29366,2419,0,12,0,0,488,4.0,8.3,351,0.35
207,Store208,Clothing,South,Offline,4245,50,1732,27117,2278,0,9,1,1,258,3.6,9.6,142,0.15
208,Store209,Furniture,South,Online,4334,30,3584,46711,2437,1,10,1,0,126,4.8,11.3,155,0.15
209,Store210,Clothing,West,Offline,4310,36,2642,7146,3905,0,12,1,0,216,4.3,5.4,433,0.35
210,Store211,Furniture,East,Offline,2776,9,2596,39061,2198,1,7,1,0,203,4.1,2.9,488,0.25
211,Store212,Clothing,West,Online,2701,12,3582,15684,4425,0,12,0,0,76,4.2,8.1,68,0.20
212,Store213,Furniture,North,Online,496,25,1668,9446,3333,0,10,0,0,448,3.6,15.2,306,0.50
213,Store214,Clothing,North,Offline,4480,10,1546,42380,2602,0,9,1,0,153,3.2,10.1,182,0.35
214,Store215,Clothing,East,Online,4831,14,752,8010,2944,0,2,1,1,402,4.0,9.5,219,0.40
215,Store216,Electronics,North,Online,800,43,733,25486,2814,0,12,1,0,159,4.2,9.9,269,0.10
216,Store217,Grocery,East,Offline,485,16,2187,25480,1731,0,2,1,0,238,3.3,10.0,182,0.25
217,Store218,Furniture,South,Online,2995,24,194,16838,1063,0,11,0,1,12,4.4,6.1,450,0.10
218,Store219,Electronics,South,Online,314,18,1562,2958,667,1,2,0,1,430,3.6,3.9,217,0.30
219,Store220,Clothing,East,Offline,2466,34,2928,38506,3676,0,2,0,0,196,3.6,4.2,444,0.15
220,Store221,Furniture,North,Offline,4398,38,1763,1853,1091,1,10,1,0,322,4.3,2.5,370,0.40
221,Store222,Electronics,East,Online,1461,28,1300,30851,4463,0,11,1,0,263,4.0,10.1,148,0.10
222,Store223,Furniture,East,Offline,4040,45,1571,37376,3364,0,3,1,1,289,3.2,13.7,184,0.30
223,Store224,Electronics,South,Online,3575,28,1443,42870,1626,0,9,0,1,100,4.2,10.0,449,0.20

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊  Adding the Risk Levels
</h2>

In [9]:
df_sales["Risk_Level"] = pd.cut(
    df_sales["Risk_Score"],
    bins=[-0.1, 0.30, 0.60, 1.0],
    labels=["Low", "Medium", "High"]
)

df_sales

      Store_ID Product_Category Region Sales_Channel  Product_Price  \
0     Store001      Electronics   East       Offline           2172
1     Store002         Clothing  South       Offline           3337
2     Store003      Electronics   East       Offline           4983
3     Store004         Clothing   East       Offline           2873
4     Store005        Furniture   West       Offline            580
5     Store006      Electronics   East       Offline           4485
6     Store007      Electronics   West        Online           3550
7     Store008        Furniture  South        Online           3944
8     Store009        Furniture   East       Offline           1032
9     Store010        Furniture  South        Online           4269
10    Store011         Clothing   West        Online           3698
11    Store012          Grocery   West       Offline            622
12    Store013        Furniture  South       Offline           1991
13    Store014         Clothing   West       Offline           2771
14    Store015         Clothing  North       Offline            909
15    Store016         Clothing  North        Online           2344
16    Store017        Furniture  North        Online           2710
17    Store018        Furniture   East       Offline           1592
18    Store019      Electronics   East        Online           3333
19    Store020          Grocery   West        Online           1898
20    Store021          Grocery   West        Online            457
21    Store022        Furniture  North       Offline           3092
22    Store023      Electronics   West        Online           3654
23    Store024         Clothing  South        Online           3711
24    Store025        Furniture   East       Offline           4447
25    Store026         Clothing   West        Online           1445
26    Store027        Furniture   West        Online            764
27    Store028      Electronics   East       Offline           3549
28    Store029         Clothing  North        Online           2898
29    Store030      Electronics   East       Offline           4927
30    Store031         Clothing  North        Online           4147
31    Store032        Furniture  North       Offline           4367
32    Store033          Grocery   East       Offline           3520
33    Store034        Furniture   West       Offline           4998
34    Store035      Electronics   West        Online           2186
35    Store036          Grocery   West       Offline           4182
36    Store037         Clothing  North       Offline           4843
37    Store038         Clothing  South        Online           2948
38    Store039        Furniture   West        Online            278
39    Store040      Electronics  South        Online           1003
40    Store041         Clothing  North        Online            900
41    Store042          Grocery   West        Online           1977
42    Store043          Grocery   West        Online           2858
43    Store044        Furniture   West       Offline           2777
44    Store045          Grocery  South       Offline           4887
45    Store046         Clothing  North       Offline           1569
46    Store047      Electronics   East        Online            934
47    Store048         Clothing   East       Offline            233
48    Store049          Grocery   West        Online           2713
49    Store050         Clothing  South        Online           2518
50    Store051          Grocery  North       Offline           2687
51    Store052      Electronics   East       Offline           1814
52    Store053          Grocery  North        Online           2659
53    Store054        Furniture   West       Offline           3590
54    Store055      Electronics   West        Online            923
55    Store056        Furniture   West        Online           4626
56    Store057      Electronics   East       Offline           4147
57    Store058      Electronics   East        Online            586
58    Store059        Furniture  North       Offline           1230
59    Store060      Electronics  North       Offline           4912
60    Store061        Furniture   West       Offline           3008
61    Store062          Grocery   West        Online           1088
62    Store063          Grocery  North        Online           4004
63    Store064      Electronics  North        Online            854
64    Store065         Clothing   West        Online           4263
65    Store066        Furniture  North        Online            571
66    Store067        Furniture  North       Offline           1556
67    Store068      Electronics   West        Online           3505
68    Store069         Clothing  North        Online           1664
69    Store070      Electronics   East        Online            293
70    Store071         Clothing   West       Offline            539
71    Store072        Furniture   West       Offline           1887
72    Store073         Clothing  South        Online           4120
73    Store074      Electronics  South       Offline           1537
74    Store075      Electronics  South       Offline           4573
75    Store076        Furniture   East        Online            266
76    Store077         Clothing  North        Online           4761
77    Store078         Clothing  South        Online           2968
78    Store079      Electronics   East        Online           3391
79    Store080      Electronics   East       Offline           1464
80    Store081          Grocery  North       Offline           4405
81    Store082          Grocery  North       Offline           3917
82    Store083      Electronics   West       Offline           3125
83    Store084         Clothing   East       Offline            314
84    Store085          Grocery   West       Offline           1194
85    Store086      Electronics  South        Online           2647
86    Store087      Electronics  North        Online           3994
87    Store088        Furniture   East       Offline           4158
88    Store089          Grocery   West       Offline           2597
89    Store090         Clothing   West       Offline            308
90    Store091        Furniture   West        Online           1467
91    Store092          Grocery   West        Online           4152
92    Store093        Furniture  North        Online           2128
93    Store094         Clothing  South        Online           3028
94    Store095         Clothing   West        Online           4072
95    Store096          Grocery   West        Online           2075
96    Store097        Furniture  North        Online            414
97    Store098          Grocery  North        Online           2602
98    Store099          Grocery   East        Online           2233
99    Store100          Grocery  South       Offline           4367
100   Store101      Electronics   West        Online           2792
101   Store102         Clothing   East        Online           3177
102   Store103          Grocery   East       Offline           1268
103   Store104      Electronics   East       Offline           2772
104   Store105        Furniture  North       Offline           1720
105   Store106          Grocery  North        Online            588
106   Store107      Electronics   East       Offline           3026
107   Store108      Electronics   West       Offline           3768
108   Store109      Electronics  North       Offline           3729
109   Store110        Furniture  North        Online           4067
110   Store111        Furniture  South        Online           4031
111   Store112      Electronics  South       Offline           2279
112   Store113         Clothing   East       Offline            462
113   Store114          Grocery  South       Offline           3562
114   Store115      Electronics   West        Online           4876
115   Store116         Clothing  North       Offline           2303
116   Store117      Electronics   East       Offline           4357
117   Store118      Electronics  North        Online           3002
118   Store119      Electronics  South       Offline            796
119   Store120          Grocery   East       Offline           2572
120   Store121          Grocery  North       Offline           3368
121   Store122        Furniture  South        Online           1863
122   Store123          Grocery  North       Offline           1508
123   Store124          Grocery  South        Online           2315
124   Store125        Furniture  South       Offline           3326
125   Store126      Electronics  North        Online           3917
126   Store127          Grocery  North        Online           4283
127   Store128      Electronics   East        Online            857
128   Store129          Grocery   West       Offline           3577
129   Store130          Grocery  South        Online           3591
130   Store131         Clothing   East       Offline            571
131   Store132        Furniture  North        Online            508
132   Store133        Furniture  North        Online            702
133   Store134      Electronics   West       Offline           4174
134   Store135        Furniture   West        Online           3632
135   Store136         Clothing  South        Online           4959
136   Store137      Electronics  North        Online           1078
137   Store138        Furniture  South        Online           1435
138   Store139        Furniture   West        Online           2308
139   Store140      Electronics  South        Online           1549
140   Store141        Furniture  North        Online           3274
141   Store142        Furniture   West       Offline           4122
142   Store143      Electronics  North        Online           3686
143   Store144          Grocery   West        Online           3327
144   Store145         Clothing   East       Offline           2782
145   Store146          Grocery   East        Online           1826
146   Store147          Grocery  South        Online           2358
147   Store148         Clothing  South        Online           4811
148   Store149      Electronics  North        Online           4741
149   Store150      Electronics   West        Online           2264
150   Store151        Furniture   West       Offline           4974
151   Store152          Grocery  North        Online            508
152   Store153      Electronics  North        Online           4637
153   Store154      Electronics  South        Online            379
154   Store155        Furniture  South        Online           3412
155   Store156          Grocery  North        Online           1918
156   Store157          Grocery  North        Online            904
157   Store158        Furniture  South       Offline           4208
158   Store159        Furniture   East       Offline           2375
159   Store160         Clothing  North       Offline           1204
160   Store161         Clothing   West       Offline           1430
161   Store162          Grocery   East        Online           4336
162   Store163      Electronics   West       Offline           2889
163   Store164        Furniture   East        Online            727
164   Store165         Clothing  North       Offline           1856
165   Store166      Electronics  South        Online           4719
166   Store167        Furniture   East        Online           1941
167   Store168        Furniture   West        Online            972
168   Store169      Electronics  North       Offline           1757
169   Store170      Electronics   East        Online           2011
170   Store171        Furniture  North        Online           1017
171   Store172         Clothing   West       Offline           4836
172   Store173      Electronics   East       Offline           2528
173   Store174         Clothing  South       Offline           2319
174   Store175      Electronics   West       Offline           4054
175   Store176         Clothing   West        Online           3332
176   Store177      Electronics   West        Online           4583
177   Store178      Electronics  North        Online           3214
178   Store179          Grocery  South       Offline           2984
179   Store180        Furniture   East       Offline            744
180   Store181         Clothing  North        Online           3992
181   Store182      Electronics  South       Offline           4698
182   Store183      Electronics  North        Online            696
183   Store184         Clothing  North       Offline           4948
184   Store185        Furniture  South        Online           2434
185   Store186      Electronics   East       Offline           1353
186   Store187         Clothing   West       Offline            909
187   Store188        Furniture   East       Offline           2827
188   Store189         Clothing  North       Offline           4475
189   Store190        Furniture  North        Online            299
190   Store191      Electronics   East        Online           1310
191   Store192      Electronics  South       Offline           1769
192   Store193      Electronics   West       Offline           1842
193   Store194        Furniture   West        Online           3860
194   Store195         Clothing   West       Offline           3254
195   Store196         Clothing  South       Offline           4914
196   Store197          Grocery   East        Online           3428
197   Store198      Electronics  North        Online           1985
198   Store199         Clothing   West       Offline           3158
199   Store200        Furniture   West        Online           3502
200   Store201        Furniture   West        Online           2530
201   Store202      Electronics  North        Online           1427
202   Store203        Furniture   West        Online           4866
203   Store204      Electronics   East        Online           1853
204   Store205        Furniture  North        Online           1219
205   Store206        Furniture   East        Online           3827
206   Store207        Furniture  North        Online           4342
207   Store208         Clothing  South       Offline           4245
208   Store209        Furniture  South        Online           4334
209   Store210         Clothing   West       Offline           4310
210   Store211        Furniture   East       Offline           2776
211   Store212         Clothing   West        Online           2701
212   Store213        Furniture  North        Online            496
213   Store214         Clothing  North       Offline           4480
214   Store215         Clothing   East        Online           4831
215   Store216      Electronics  North        Online            800
216   Store217          Grocery   East       Offline            485
217   Store218        Furniture  South        Online           2995
218   Store219      Electronics  South        Online            314
219   Store220         Clothing   East       Offline           2466
220   Store221        Furniture  North       Offline           4398
221   Store222      Electronics   East        Online           1461
222   Store223        Furniture   East       Offline           4040
223   Store224      Electronics  South        Online           3575
224   Store225        Furniture   West       Offline           1300
225   Store226          Grocery  North        Online           4730
226   Store227      Electronics   East       Offline            917
227   Store228         Clothing  South        Online           1143
228   Store229          Grocery  South        Online           3293
229   Store230         Clothing   East        Online            473
230   Store231          Grocery  South        Online           1903
231   Store232        Furniture   East       Offline           3410
232   Store233          Grocery  South        Online           3167
233   Store234         Clothing  South        Online           3186
234   Store235        Furniture  South       Offline           3677
235   Store236          Grocery  North        Online           1020
236   Store237      Electronics   West        Online           2002
237   Store238          Grocery   East        Online           1208
238   Store239      Electronics  South       Offline            409
239   Store240      Electronics  North       Offline           4671
240   Store241         Clothing   West       Offline            535
241   Store242         Clothing  South        Online            684
242   Store243        Furniture  South       Offline            719
243   Store244      Electronics   East        Online           4092
244   Store245         Clothing   East       Offline           3936
245   Store246      Electronics   East        Online            491
246   Store247        Furniture  North       Offline           1756
247   Store248          Grocery   West       Offline           2475
248   Store249          Grocery   East        Online           3125
249   Store250          Grocery  North        Online           1930
250   Store251        Furniture   East        Online            304
251   Store252         Clothing   West       Offline            650
252   Store253        Furniture  North       Offline           4438
253   Store254          Grocery   East       Offline            235
254   Store255         Clothing   East        Online            502
255   Store256      Electronics  South        Online           1430
256   Store257         Clothing  North        Online           1426
257   Store258      Electronics   East        Online           4067
258   Store259          Grocery  North        Online           4431
259   Store260          Grocery   East       Offline           4799
260   Store261        Furniture  North        Online           2984
261   Store262         Clothing   East        Online           2903
262   Store263          Grocery  North       Offline           4644
263   Store264          Grocery   West       Offline           4433
264   Store265      Electronics   West        Online           3209
265   Store266      Electronics  South        Online            507
266   Store267        Furniture  North        Online           4897
267   Store268        Furniture  North       Offline            325
268   Store269         Clothing   West       Offline           2090
269   Store270          Grocery  North       Offline           4141
270   Store271          Grocery   East        Online            889
271   Store272        Furniture   West       Offline            487
272   Store273          Grocery   East       Offline           4541
273   Store274      Electronics   East        Online           4263
274   Store275      Electronics  North       Offline           1575
275   Store276         Clothing  North       Offline           2907
276   Store277      Electronics  South        Online            477
277   Store278          Grocery   West       Offline            349
278   Store279         Clothing   West        Online           1039
279   Store280          Grocery  North        Online           1561
280   Store281          Grocery   West       Offline           2093
281   Store282         Clothing  North        Online           1554
282   Store283        Furniture   East       Offline            228
283   Store284         Clothing   West        Online           2079
284   Store285         Clothing   West       Offline            518
285   Store286         Clothing   West        Online           4139
286   Store287         Clothing   West        Online           3522
287   Store288         Clothing   West       Offline            805
288   Store289          Grocery   East        Online           2470
289   Store290         Clothing   West        Online           3921
290   Store291          Grocery   West        Online           1764
291   Store292      Electronics  South       Offline           2699
292   Store293      Electronics  North       Offline           4014

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Store in CSV file
</h2>

In [11]:
df_sales.to_csv("sales_prediction_with_risk_score.csv", index=False)