In [1]:
import requests
import pandas as pd

In [2]:
url = "https://open.er-api.com/v6/latest/USD"

response = requests.get(url)

print(response.status_code)

200

In [3]:
data = response.json()

print(data.keys())

dict_keys(['result', 'provider', 'documentation', 'terms_of_use', 'time_last_update_unix', 'time_last_update_utc', 'time_next_update_unix', 'time_next_update_utc', 'time_eol_unix', 'base_code', 'rates'])

In [4]:
rates = data["rates"]

df = pd.DataFrame(rates.items(), columns=["Currency", "Exchange Rate"])

df

    Currency  Exchange Rate
0        USD       1.000000
1        AED       3.672500
2        AFN      66.089678
3        ALL      82.254308
4        AMD     366.848196
..       ...            ...
161      YER     237.649847
162      ZAR      16.378420
163      ZMW      18.067206
164      ZWG      26.785300
165      ZWL      26.785300

[166 rows x 2 columns]

In [5]:
pd.set_option("display.max_rows", None)

df

    Currency  Exchange Rate
0        USD   1.000000e+00
1        AED   3.672500e+00
2        AFN   6.608968e+01
3        ALL   8.225431e+01
4        AMD   3.668482e+02
5        ANG   1.790000e+00
6        AOA   9.249787e+02
7        ARS   1.474737e+03
8        AUD   1.436221e+00
9        AWG   1.790000e+00
10       AZN   1.700050e+00
11       BAM   1.712843e+00
12       BBD   2.000000e+00
13       BDT   1.233232e+02
14       BGN   1.712843e+00
15       BHD   3.760000e-01
16       BIF   2.992640e+03
17       BMD   1.000000e+00
18       BND   1.291353e+00
19       BOB   1.033342e+01
20       BRL   5.099215e+00
21       BSD   1.000000e+00
22       BTN   9.623637e+01
23       BWP   1.372116e+01
24       BYN   2.870264e+00
25       BZD   2.000000e+00
26       CAD   1.406611e+00
27       CDF   2.267866e+03
28       CHF   8.102210e-01
29       CLF   2.359300e-02
30       CLP   9.325329e+02
31       CNH   6.774329e+00
32       CNY   6.782028e+00
33       COP   3.240624e+03
34       CRC   4.559955e+02
35       CUP   2.400000e+01
36       CVE   9.656599e+01
37       CZK   2.125127e+01
38       DJF   1.777210e+02
39       DKK   6.538212e+00
40       DOP   5.891024e+01
41       DZD   1.332462e+02
42       EGP   5.072363e+01
43       ERN   1.500000e+01
44       ETB   1.595223e+02
45       EUR   8.757640e-01
46       FJD   2.231029e+00
47       FKP   7.470190e-01
48       FOK   6.538566e+00
49       GBP   7.470140e-01
50       GEL   2.632188e+00
51       GGP   7.470190e-01
52       GHS   1.151719e+01
53       GIP   7.470190e-01
54       GMD   7.431328e+01
55       GNF   8.780880e+03
56       GTQ   7.635681e+00
57       GYD   2.092132e+02
58       HKD   7.837866e+00
59       HNL   2.681264e+01
60       HRK   6.598435e+00
61       HTG   1.306896e+02
62       HUF   3.144406e+02
63       IDR   1.808030e+04
64       ILS   3.009347e+00
65       IMP   7.470190e-01
66       INR   9.624159e+01
67       IQD   1.309596e+03
68       IRR   1.264884e+06
69       ISK   1.255528e+02
70       JEP   7.470190e-01
71       JMD   1.588814e+02
72       JOD   7.090000e-01
73       JPY   1.621718e+02
74       KES   1.292468e+02
75       KGS   8.746143e+01
76       KHR   4.049083e+03
77       KID   1.435449e+00
78       KMF   4.308471e+02
79       KRW   1.490484e+03
80       KWD   3.094620e-01
81       KYD   8.333330e-01
82       KZT   4.692185e+02
83       LAK   2.238698e+04
84       LBP   8.950000e+04
85       LKR   3.359517e+02
86       LRD   1.820065e+02
87       LSL   1.637855e+01
88       LYD   6.403673e+00
89       MAD   9.330189e+00
90       MDL   1.759308e+01
91       MGA   4.283422e+03
92       MKD   5.392533e+01
93       MMK   2.103056e+03
94       MNT   3.620349e+03
95       MOP   8.072765e+00
96       MRU   4.008291e+01
97       MUR   4.726744e+01
98       MVR   1.544771e+01
99       MWK   1.745628e+03
100      MXN   1.743898e+01
101      MYR   4.077940e+00
102      MZN   6.353985e+01
103      NAD   1.637855e+01
104      NGN   1.382584e+03
105      NIO   3.675998e+01
106      NOK   9.690655e+00
107      NPR   1.539782e+02
108      NZD   1.721300e+00
109      OMR   3.844970e-01
110      PAB   1.000000e+00
111      PEN   3.407729e+00
112      PGK   4.393155e+00
113      PHP   6.169592e+01
114      PKR   2.782116e+02
115      PLN   3.791078e+00
116      PYG   6.072721e+03
117      QAR   3.640000e+00
118      RON   4.591665e+00
119      RSD   1.029849e+02
120      RUB   7.749521e+01
121      RWF   1.471295e+03
122      SAR   3.750000e+00
123      SBD   7.974975e+00
124      SCR   1.418509e+01
125      SDG   4.495165e+02
126      SEK   9.661651e+00
127      SGD   1.291353e+00
128      SHP   7.470190e-01
129      SLE   2.432820e+01
130      SLL   2.432820e+04
131      SOS   5.720253e+02
132      SRD   3.786053e+01
133      SSP   4.792431e+03
134      STN   2.145619e+01
135      SYP   1.216859e+02
136      SZL   1.637855e+01
137      THB   3.346807e+01
138      TJS   9.241522e+00
139      TMT   3.500015e+00
140      TND   2.953638e+00
141      TOP   2.387652e+00
142      TRY   4.703304e+01
143      TTD   6.778952e+00
144      TVD   1.435449e+00
145      TWD   3.214809e+01
146      TZS   2.605801e+03
147      UAH   4.490211e+01
148      UGX   3.673063e+03
149      UYU   4.035382e+01
150      UZS   1.214356e+04
151      VES   7.257470e+02
152      VND   2.620597e+04
153      VUV   1.198866e+02
154      WST   2.725221e+00
155      XAF   5.744628e+02
156      XCD   2.700000e+00
157      XCG   1.790000e+00
158      XDR   7.367520e-01
159      XOF   5.744628e+02
160      XPF   1.045065e+02
161      YER   2.376498e+02
162      ZAR   1.637842e+01
163      ZMW   1.806721e+01
164      ZWG   2.678530e+01
165      ZWL   2.678530e+01

In [6]:
df.to_csv("Exchange_Rates.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!