In [12]:
import requests
import pandas as pd
import json

In [16]:
url = "https://countriesnow.space/api/v0.1/countries/capital"

response = requests.get(url)

data = response.json()

countries = data["data"]

df = pd.DataFrame(countries)

df.head(20)

                   name           capital iso2 iso3
0           Afghanistan             Kabul   AF  AFG
1         Aland Islands         Mariehamn   AX  ALA
2               Albania            Tirana   AL  ALB
3               Algeria           Algiers   DZ  DZA
4               Andorra  Andorra la Vella   AD  AND
5                Angola            Luanda   AO  AGO
6              Anguilla        The Valley   AI  AIA
7            Antarctica                     AQ  ATA
8   Antigua and Barbuda        St. John's   AG  ATG
9             Argentina      Buenos Aires   AR  ARG
10              Armenia           Yerevan   AM  ARM
11                Aruba        Oranjestad   AW  ABW
12            Australia          Canberra   AU  AUS
13              Austria            Vienna   AT  AUT
14           Azerbaijan              Baku   AZ  AZE
15              Bahamas            Nassau   BS  BHS
16              Bahrain            Manama   BH  BHR
17           Bangladesh             Dhaka   BD  BGD
18             Barbados        Bridgetown   BB  BRB
19              Belarus             Minsk   BY  BLR

In [17]:
df

                  name           capital iso2 iso3
0          Afghanistan             Kabul   AF  AFG
1        Aland Islands         Mariehamn   AX  ALA
2              Albania            Tirana   AL  ALB
3              Algeria           Algiers   DZ  DZA
4              Andorra  Andorra la Vella   AD  AND
..                 ...               ...  ...  ...
245  Wallis and Futuna          Mata Utu   WF  WLF
246     Western Sahara          El-Aaiun   EH  ESH
247              Yemen             Sanaa   YE  YEM
248             Zambia            Lusaka   ZM  ZMB
249           Zimbabwe            Harare   ZW  ZWE

[250 rows x 4 columns]

In [18]:
df.to_csv("Countries.csv", index=False)
print("CSV Saved Successfully!")

CSV Saved Successfully!