In [15]:
import numpy as np
import pandas as pd

In [17]:
import numpy as np
import pandas as pd

np.random.seed(54)

n_documents = 10000

data = {

    # Basic Information
    "Document_ID": [f"DOC{i:05d}" for i in range(1, n_documents+1)],

    "Organization_Type": np.random.choice(
        ["University","Company","Government","Hospital","Bank","NGO"],
        n_documents,
        p=[0.25,0.30,0.15,0.10,0.10,0.10]
    ),

    "Department": np.random.choice(
        ["HR","Finance","Legal","Academic","Research","Administration","Operations"],
        n_documents
    ),

    "Document_Type": np.random.choice(
        ["Project Report","Research Paper","Application",
         "Policy Document","Invoice","Legal Document",
         "Medical Report","Resume","Contract"],
        n_documents
    ),

    "Submitted_By": np.random.choice(
        ["Student","Employee","Faculty","Customer","Vendor","Citizen"],
        n_documents
    ),

    "Language": np.random.choice(
        ["English","Hindi","Other"],
        n_documents,
        p=[0.75,0.20,0.05]
    ),

    # Document Details
    "Total_Pages": np.random.randint(2,150,n_documents),

    "Mandatory_Sections_Present": np.random.choice(
        ["Yes","No"],
        n_documents,
        p=[0.85,0.15]
    ),

    "Missing_Sections_Count": np.random.poisson(1,n_documents),

    "Policy_Violations_Count": np.random.poisson(2,n_documents),

    # Quality Features
    "Formatting_Score": np.clip(
        np.random.normal(85,10,n_documents),40,100
    ).round(1),

    "Grammar_Score": np.clip(
        np.random.normal(82,12,n_documents),40,100
    ).round(1),

    "Plagiarism_Percentage": np.clip(
        np.random.normal(15,10,n_documents),0,60
    ).round(),

    "Document_Completeness": np.clip(
        np.random.normal(90,8,n_documents),40,100
    ).round(1),

    "Readability_Score": np.clip(
        np.random.normal(80,10,n_documents),40,100
    ).round(1),

    # Verification
    "Signature_Present": np.random.choice(
        ["Yes","No"],
        n_documents,
        p=[0.90,0.10]
    ),

    "Required_Attachments": np.random.choice(
        ["Yes","No"],
        n_documents,
        p=[0.88,0.12]
    ),

    "Submission_On_Time": np.random.choice(
        ["Yes","No"],
        n_documents,
        p=[0.80,0.20]
    ),

    "Policy_Version": np.random.choice(
        ["v1.0","v2.0","v3.0","v4.0"],
        n_documents
    ),

    "Sensitive_Data_Detected": np.random.choice(
        ["Yes","No"],
        n_documents,
        p=[0.08,0.92]
    )
}

df = pd.DataFrame(data)

df

,Document_ID,Organization_Type,Department,Document_Type,Submitted_By,Language,Total_Pages,Mandatory_Sections_Present,Missing_Sections_Count,Policy_Violations_Count,Formatting_Score,Grammar_Score,Plagiarism_Percentage,Document_Completeness,Readability_Score,Signature_Present,Required_Attachments,Submission_On_Time,Policy_Version,Sensitive_Data_Detected
0,DOC00001,Company,Administration,Policy Document,Citizen,Other,103,Yes,1,4,96.3,78.8,19.0,82.2,56.9,Yes,Yes,Yes,v4.0,No
1,DOC00002,Company,Administration,Medical Report,Employee,English,85,No,0,2,81.8,77.9,16.0,100.0,90.1,Yes,Yes,Yes,v2.0,No
2,DOC00003,University,Research,Invoice,Vendor,English,62,Yes,1,2,86.1,77.6,19.0,100.0,81.5,Yes,Yes,No,v2.0,No
3,DOC00004,Company,Research,Contract,Citizen,English,132,No,1,1,98.1,77.5,23.0,81.2,80.0,Yes,No,Yes,v2.0,Yes
4,DOC00005,University,Legal,Policy Document,Citizen,English,133,No,1,1,82.7,93.3,31.0,81.1,82.5,Yes,No,No,v1.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,DOC09996,University,HR,Legal Document,Customer,English,26,Yes,0,2,76.8,78.6,5.0,85.7,96.5,Yes,Yes,Yes,v2.0,No
9996,DOC09997,Hospital,Academic,Legal Document,Customer,English,7,Yes,3,0,86.6,89.2,7.0,95.2,94.2,Yes,Yes,Yes,v3.0,No
9997,DOC09998,Government,Administration,Contract,Student,English,75,Yes,1,2,95.5,81.2,0.0,86.2,68.0,Yes,Yes,Yes,v1.0,No
9998,DOC09999,Bank,Operations,Invoice,Employee,English,72,Yes,2,0,83.3,80.5,0.0,94.1,65.2,Yes,Yes,Yes,v1.0,No
9999,DOC10000,Company,Operations,Application,Citizen,English,6,Yes,0,2,88.4,72.5,32.0,90.1,94.7,Yes,Yes,No,v4.0,No

In [19]:
# Risk Score Calculation

df["Risk_Score"] = (

    # Missing Sections (Maximum Impact)
    df["Missing_Sections_Count"] * 8

    # Policy Violations
    + df["Policy_Violations_Count"] * 7

    # Plagiarism
    + df["Plagiarism_Percentage"] * 0.50

    # Poor Formatting
    + (100 - df["Formatting_Score"]) * 0.15

    # Poor Grammar
    + (100 - df["Grammar_Score"]) * 0.10

    # Incomplete Document
    + (100 - df["Document_Completeness"]) * 0.20

    # Poor Readability
    + (100 - df["Readability_Score"]) * 0.10

    # Mandatory Sections Missing
    + np.where(df["Mandatory_Sections_Present"] == "No", 12, 0)

    # Signature Missing
    + np.where(df["Signature_Present"] == "No", 8, 0)

    # Required Attachments Missing
    + np.where(df["Required_Attachments"] == "No", 8, 0)

    # Late Submission
    + np.where(df["Submission_On_Time"] == "No", 6, 0)

    # Sensitive Data Found
    + np.where(df["Sensitive_Data_Detected"] == "Yes", 10, 0)

)

# Keep score between 0 and 100
df["Risk_Score"] = np.clip(df["Risk_Score"], 0, 100).round(2)

In [20]:
df

,Document_ID,Organization_Type,Department,Document_Type,Submitted_By,Language,Total_Pages,Mandatory_Sections_Present,Missing_Sections_Count,Policy_Violations_Count,...,Grammar_Score,Plagiarism_Percentage,Document_Completeness,Readability_Score,Signature_Present,Required_Attachments,Submission_On_Time,Policy_Version,Sensitive_Data_Detected,Risk_Score
0,DOC00001,Company,Administration,Policy Document,Citizen,Other,103,Yes,1,4,...,78.8,19.0,82.2,56.9,Yes,Yes,Yes,v4.0,No,56.04
1,DOC00002,Company,Administration,Medical Report,Employee,English,85,No,0,2,...,77.9,16.0,100.0,90.1,Yes,Yes,Yes,v2.0,No,39.93
2,DOC00003,University,Research,Invoice,Vendor,English,62,Yes,1,2,...,77.6,19.0,100.0,81.5,Yes,Yes,No,v2.0,No,43.68
3,DOC00004,Company,Research,Contract,Citizen,English,132,No,1,1,...,77.5,23.0,81.2,80.0,Yes,No,Yes,v2.0,Yes,64.80
4,DOC00005,University,Legal,Policy Document,Citizen,English,133,No,1,1,...,93.3,31.0,81.1,82.5,Yes,No,No,v1.0,No,65.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,DOC09996,University,HR,Legal Document,Customer,English,26,Yes,0,2,...,78.6,5.0,85.7,96.5,Yes,Yes,Yes,v2.0,No,25.33
9996,DOC09997,Hospital,Academic,Legal Document,Customer,English,7,Yes,3,0,...,89.2,7.0,95.2,94.2,Yes,Yes,Yes,v3.0,No,32.13
9997,DOC09998,Government,Administration,Contract,Student,English,75,Yes,1,2,...,81.2,0.0,86.2,68.0,Yes,Yes,Yes,v1.0,No,30.51
9998,DOC09999,Bank,Operations,Invoice,Employee,English,72,Yes,2,0,...,80.5,0.0,94.1,65.2,Yes,Yes,Yes,v1.0,No,25.12
9999,DOC10000,Company,Operations,Application,Citizen,English,6,Yes,0,2,...,72.5,32.0,90.1,94.7,Yes,Yes,No,v4.0,No,43.00

In [21]:
df.to_csv("policy_compliance_checker.csv", index = False)